import React from 'react';
import { GratingLobeSolution, SimulationParameters } from '../types/microwave';

interface Props {
  params: SimulationParameters;
  onChangeParams: (p: SimulationParameters)=>void;
  onResetDefaults: ()=>void;
  effectiveDOverLambda: number;
  gratingLobes: GratingLobeSolution[];
}

export const AdvancedParametersPanel:React.FC<Props>=({params,onChangeParams,onResetDefaults,effectiveDOverLambda,gratingLobes})=>{
  const set=(patch:Partial<SimulationParameters>)=>onChangeParams({...params,...patch});
  const setAmp=(i:number,v:number)=>{const a=[...params.amplitudeWeights] as [number,number,number,number];a[i]=Math.max(0,Math.min(1.5,v));set({amplitudeWeights:a});};
  const setPhase=(i:number,v:number)=>{const a=[...params.phaseErrorsDeg] as [number,number,number,number];a[i]=Math.max(-45,Math.min(45,v));set({phaseErrorsDeg:a});};
  const toggle=()=>set({isNonIdealMode:!params.isNonIdealMode, amplitudeWeights:!params.isNonIdealMode?[1,.92,.88,.95]:[1,1,1,1], phaseErrorsDeg:!params.isNonIdealMode?[0,4.5,-5.2,3.8]:[0,0,0,0]});
  return <div className="rounded-xl border border-slate-800 bg-slate-900/90 p-3 sm:p-5 shadow-xl">
    <div className="flex flex-wrap justify-between gap-3 border-b border-slate-800 pb-3"><div><h3 className="font-bold text-slate-100">Exploración de parámetros y modelo no ideal</h3><p className="text-xs text-slate-400">Los errores precargados son solo un ejemplo ilustrativo, no propiedades universales del FR4.</p></div><div className="flex gap-2"><button onClick={toggle} className={`px-3 py-2 rounded border text-xs ${params.isNonIdealMode?'border-rose-400 text-rose-300 bg-rose-950/30':'border-emerald-500 text-emerald-300'}`}>{params.isNonIdealMode?'Modelo no ideal':'Modelo ideal'}</button><button onClick={onResetDefaults} className="px-3 py-2 rounded border border-slate-700 text-xs">Restablecer</button></div></div>
    {gratingLobes.length>0&&<div className="mt-3 rounded-lg border border-amber-500/50 bg-amber-950/30 p-3 text-xs text-amber-200"><strong>Grating lobe detectado:</strong> {gratingLobes.map(g=>`m=${g.m}, θ=${g.thetaDeg>=0?'+':''}${g.thetaDeg.toFixed(1)}°`).join(' · ')}. La detección se obtiene de kd·sinθ+β=2πm, no de una regla fija d&gt;λ/2.</div>}
    <div className="mt-4 grid md:grid-cols-2 xl:grid-cols-4 gap-4">
      <label className="rounded-lg bg-slate-950 border border-slate-800 p-3 text-xs"><span className="flex justify-between"><span>Frecuencia</span><strong className="text-cyan-300">{params.frequencyGhz.toFixed(2)} GHz</strong></span><input className="w-full mt-2 accent-cyan-400" type="range" min="1" max="5" step="0.05" value={params.frequencyGhz} onChange={e=>set({frequencyGhz:Number(e.target.value)})}/></label>
      <div className="rounded-lg bg-slate-950 border border-slate-800 p-3 text-xs"><div className="font-semibold">Modo de separación</div><div className="mt-2 flex gap-2"><button onClick={()=>set({spacingMode:'normalized'})} className={`flex-1 rounded border px-2 py-2 ${params.spacingMode==='normalized'?'border-cyan-400 text-cyan-300':'border-slate-700'}`}>d/λ fijo</button><button onClick={()=>set({spacingMode:'physical'})} className={`flex-1 rounded border px-2 py-2 ${params.spacingMode==='physical'?'border-cyan-400 text-cyan-300':'border-slate-700'}`}>d físico fijo</button></div><div className="mt-2 text-slate-500">Actual: d/λ={effectiveDOverLambda.toFixed(3)}</div></div>
      {params.spacingMode==='normalized'?<label className="rounded-lg bg-slate-950 border border-slate-800 p-3 text-xs"><span className="flex justify-between"><span>d/λ</span><strong className="text-emerald-300">{params.dOverLambda.toFixed(2)}</strong></span><input className="w-full mt-2 accent-emerald-400" type="range" min="0.25" max="1.1" step="0.01" value={params.dOverLambda} onChange={e=>set({dOverLambda:Number(e.target.value)})}/><div className="mt-1 text-slate-500">La geometría se reescala con λ.</div></label>:<label className="rounded-lg bg-slate-950 border border-slate-800 p-3 text-xs"><span className="flex justify-between"><span>d físico</span><strong className="text-emerald-300">{params.physicalSpacingMm.toFixed(1)} mm</strong></span><input className="w-full mt-2 accent-emerald-400" type="range" min="20" max="120" step="0.5" value={params.physicalSpacingMm} onChange={e=>set({physicalSpacingMm:Number(e.target.value)})}/><div className="mt-1 text-slate-500">Al variar f cambia d/λ.</div></label>}
      <label className="rounded-lg bg-slate-950 border border-slate-800 p-3 text-xs"><span className="flex justify-between"><span>Patrón elemento q</span><strong className="text-amber-300">{params.elementPowerQ.toFixed(1)}</strong></span><input className="w-full mt-2 accent-amber-400" type="range" min="0" max="2.5" step="0.1" value={params.elementPowerQ} onChange={e=>set({elementPowerQ:Number(e.target.value)})}/><div className="mt-1 text-slate-500">q=0: isotrópico en el plano; q=1: modelo pedagógico cosθ.</div></label>
    </div>
    {params.isNonIdealMode&&<div className="mt-4 rounded-lg border border-rose-900 bg-rose-950/20 p-4"><div className="text-xs font-semibold text-rose-300">Errores editables por salida</div><div className="mt-3 grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{[0,1,2,3].map(i=><div key={i} className="rounded bg-slate-950 border border-slate-800 p-3 text-xs"><div className="font-bold">O{i+1}</div><label className="block mt-2">Factor amplitud<input type="number" step="0.01" min="0" max="1.5" value={params.amplitudeWeights[i]} onChange={e=>setAmp(i,Number(e.target.value))} className="mt-1 w-full bg-slate-900 border border-slate-700 rounded px-2 py-1"/></label><label className="block mt-2">Δφ [°]<input type="number" step="0.5" min="-45" max="45" value={params.phaseErrorsDeg[i]} onChange={e=>setPhase(i,Number(e.target.value))} className="mt-1 w-full bg-slate-900 border border-slate-700 rounded px-2 py-1"/></label></div>)}</div></div>}
  </div>;
};